AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway REST API con VPC Link y Lambda Authorizer

Parameters:
  NlbDns:
    Type: String

  NlbArn:
    Type: String

  AuthorizerLambdaArn:
    Type: String
    Description: ARN del Lambda Authorizer

Resources:

  VpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: gamer-vpc-link
      TargetArns:
        - !Ref NlbArn

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: gamer-rest-api
      EndpointConfiguration:
        Types:
          - REGIONAL

  Authorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: gamer-lambda-authorizer
      Type: TOKEN
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref RestApi
      AuthorizerUri: !Sub
        - arn:aws:apigateway:${Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
        - {
            Region: !Ref "AWS::Region",
            LambdaArn: !Ref AuthorizerLambdaArn
          }
  
  #Resource /auth
  AuthResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: 
        Fn::GetAtt:
          - RestApi
          - RootResourceId
      PathPart: auth

  #Resource /auth/changepassword post
  ChangePassResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref AuthResource
      PathPart: changepassword

  #Resource /auth/deactivateuser post
  DeactivateUserResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref AuthResource
      PathPart: deactivateuser

  #Resource /auth/login post
  LoginResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref AuthResource
      PathPart: login

  #Resource /auth/register post
  RegisterResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref AuthResource
      PathPart: register

  #Resource /orders post
  OrdersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: 
        Fn::GetAtt:
          - RestApi
          - RootResourceId
      PathPart: orders

  #Resource /orders/{user_id} get
  OrderUserResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref OrdersResource
      PathPart: '{user_id}'

  #Resource /orders/detail
  DetailResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref OrdersResource
      PathPart: detail

  #Resource /orders/detail/{order_id} get
  OrderIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref DetailResource
      PathPart: '{order_id}'
  
  #Resource /products
  ProductsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: 
        Fn::GetAtt:
          - RestApi
          - RootResourceId
      PathPart: products

  ProductMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ProductsResource
      HttpMethod: GET
      AuthorizationType: NONE #Colocar CUSTOM si se va a usar la Lambda Auth
      # AuthorizationId: !Ref Authorizer
      Integration:
        Type: HTTP
        IntegrationHttpMethod: GET
        Uri: !Sub "http://${NlbDns}:5003/products"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VpcLink
        PassthroughBehavior: WHEN_NO_MATCH
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
  
  #Resource /products/{product_id} get
  ProductIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref ProductsResource
      PathPart: '{product_id}'

  #Resource /products/coins get
  CoinsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref ProductsResource
      PathPart: coins

  #Resource /products/coins/{videogames_name} get
  GamesNameResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref CoinsResource
      PathPart: '{videogames_name}'

  #Resource /products/coins/games-list get
  GamesListResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref CoinsResource
      PathPart: games-list

  #Resource /products/videogames get
  VideogamesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref ProductsResource
      PathPart: videogames
      
  VideogamesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref VideogamesResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: HTTP
        IntegrationHttpMethod: GET
        Uri: !Sub "http://${NlbDns}:5003/products/videogames"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VpcLink
        PassthroughBehavior: WHEN_NO_MATCH
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200

  #Resource /shoppingcart post
  CartResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: 
        Fn::GetAtt:
          - RestApi
          - RootResourceId
      PathPart: shoppingcart
  #Resource /shoppingcart/update post

  #Resource /users
  UsersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: 
        Fn::GetAtt:
          - RestApi
          - RootResourceId
      PathPart: users
  #Resource /users/{user_id} get

  #Resource /wallet
  WalletResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: 
        Fn::GetAtt:
          - RestApi
          - RootResourceId
      PathPart: wallet
  #Resource /wallet/{user_id} get
  WalletUserIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref WalletResource
      PathPart: '{user_id}'

  #Resource /wallet/{user_id}/add post
  WalletAddResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref WalletUserIdResource
      PathPart: add

  #Resource /wallet/{user_id}/deduct post
  WalletDeductResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref WalletUserIdResource
      PathPart: deduct

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - ProductMethod
      - VideogamesMethod
    Properties:
      RestApiId: !Ref RestApi
      StageName: prod
  
  LambdaPermissionForApiGateway:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AuthorizerLambdaArn
      Principal: apigateway.amazonaws.com

Outputs:
  RestApiId:
    Value: !Ref RestApi

  ApiEndpoint:
    Description: URL publica del API Gateway
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
