AWSTemplateFormatVersion: '2010-09-09'
Description: NLB privado para Fargate + integracion con API Gateway (VPC Link)

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

  NlbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:

  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: gamer-nlb
      Type: network
      Scheme: internal
      Subnets: !Ref SubnetIds
      LoadBalancerAttributes:
        - Key: load_balancing.cross_zone.enabled
          Value: true
      Tags:
        - Key: Name
          Value: gamer-nlb

  NlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: gamer-tg
      Protocol: TCP
      Port: 5000
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckProtocol: TCP
      HealthCheckPort: traffic-port
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 20
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Tags:
        - Key: Name
          Value: gamer-tg

  NlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 5000
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NlbTargetGroup

Outputs:
  NlbArn:
    Value: !Ref NetworkLoadBalancer

  NlbDnsName:
    Value: !GetAtt NetworkLoadBalancer.DNSName

  TargetGroupArn:
    Value: !Ref NlbTargetGroup

  NlbListenerArn:
    Value: !Ref NlbListener