AWSTemplateFormatVersion: '2010-09-09'
Description: NLB privado para Fargate + integracion con API Gateway (VPC Link)

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

  NlbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:

  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: gamer-nlb
      Type: network
      Scheme: internal
      Subnets: !Ref SubnetIds
      LoadBalancerAttributes:
        - Key: load_balancing.cross_zone.enabled
          Value: true
      Tags:
        - Key: Name
          Value: gamer-nlb

  #Auth - Listener and Target Group
  NlbTargetGroupAuth:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: gamer-tg-auth
      Protocol: TCP
      Port: 5000
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckProtocol: TCP
      HealthCheckPort: traffic-port
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 20
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Tags:
        - Key: Name
          Value: gamer-tg-auth

  NlbListenerAuth:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 5001
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NlbTargetGroupAuth
  
  #Order - Listener and Target Group
  NlbTargetGroupOrder:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: gamer-tg-order
      Protocol: TCP
      Port: 5000
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckProtocol: TCP
      HealthCheckPort: traffic-port
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 20
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Tags:
        - Key: Name
          Value: gamer-tg-order

  NlbListenerOrder:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 5002
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NlbTargetGroupOrder
  
  #Product - Listener and Target Group
  NlbTargetGroupProduct:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: gamer-tg-product
      Protocol: TCP
      Port: 5000
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckProtocol: TCP
      HealthCheckPort: traffic-port
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 20
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Tags:
        - Key: Name
          Value: gamer-tg-product

  NlbListenerProduct:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 5003
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NlbTargetGroupProduct

  #Wallet - Listener and Target Group
  NlbTargetGroupWallet:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: gamer-tg-wallet
      Protocol: TCP
      Port: 5000
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckProtocol: TCP
      HealthCheckPort: traffic-port
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 20
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Tags:
        - Key: Name
          Value: gamer-tg-wallet

  NlbListenerWallet:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 5004
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NlbTargetGroupWallet

Outputs:
  NlbArn:
    Value: !Ref NetworkLoadBalancer

  NlbDnsName:
    Value: !GetAtt NetworkLoadBalancer.DNSName

  TargetGroupArnAuth:
    Value: !Ref NlbTargetGroupAuth
  
  TargetGroupArnOrder:
    Value: !Ref NlbTargetGroupOrder

  TargetGroupArnProduct:
    Value: !Ref NlbTargetGroupProduct
  
  TargetGroupArnWallet:
    Value: !Ref NlbTargetGroupWallet

  # NlbListenerArnAuth:
  #   Value: !Ref NlbListenerAuth